- name: Configure local server
  hosts: local
  become: yes

  tasks:

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create webpage
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Project 15 - Automate Server Configuration with Ansible</h1>
